[default]
# 通用设置
SECRET_ID = "@format {env[TENCENTCLOUD_SECRET_ID]}"
SECRET_KEY = "@format {env[TENCENTCLOUD_SECRET_KEY]}"
UIN = "@format {env[TENCENTCLOUD_UIN]}"
APPID = "@format {env[TENCENTCLOUD_APPID]}"
DEFAULT_REGION = "@format {env[TENCENTCLOUD_REGION]}"

# 云函数运行环境
SCF_RUNTIME = "@format {env[SCF_RUNTIME]}"
SCF_DEFAULT_FUNCTION_NAME = "@format {env[SCF_FUNCTIONNAME]}"