component: scf
name: event-source
inputs:
  name: ${app}-${name}
  src: ./
  description: 事件源示例
  handler: index.main_handler
  runtime: Python3.7
  namespace: default
  region: ap-shanghai
  memorySize: 64
  timeout: 3